# Generated by Django 5.0.3 on 2024-03-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.tag'),
        ),
    ]
