# Generated by Django 5.0.3 on 2024-03-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_tag_options_task_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
